export const GET_TOP_STORIES = 'cont/HomePage/GET_TOP_STORIES';
export const GET_TOP_STORIES_LOADING = 'cont/HomePage/GET_TOP_STORIES_LOADING';
export const GET_TOP_STORIES_SUCCESSFUL = 'cont/HomePage/GET_TOP_STORIES_SUCCESSFUL';
export const GET_TOP_STORIES_ERROR = 'cont/HomePage/GET_TOP_STORIES_ERROR';

export const CLEAR_STORIES = 'cont/HomePage/CLEAR_STORIES';
export const GET_STORY_DETAILS = 'cont/HomePage/GET_STORY_DETAILS';
export const GET_STORY_DETAILS_INFINITE = 'cont/HomePage/GET_STORY_DETAILS_INFINITE';
export const GET_STORY_DETAILS_LOADING = 'cont/HomePage/GET_STORY_DETAILS_LOADING';
export const GET_STORY_DETAILS_SUCCESSFUL = 'cont/HomePage/GET_STORY_DETAILS_SUCCESSFUL';
export const GET_STORY_DETAILS_ERROR = 'cont/HomePage/GET_STORY_DETAILS_ERROR';
